# Generated by Django 4.1 on 2022-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_word_level_alter_word_type_delete_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(blank=True, choices=[(1, 'easy'), (2, 'medium'), (1, 'hard')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(blank=True, choices=[(1, 'глагол'), (2, 'существительное'), (3, 'прилагательное'), (4, 'наречие'), (5, 'местоимение'), (6, 'другое')], max_length=10, null=True),
        ),
    ]
