# Generated by Django 4.1 on 2022-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_word_level_alter_word_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(blank=True, choices=[('a', 'глагол'), ('b', 'существительное'), ('c', 'прилагательное'), ('d', 'наречие'), ('e', 'местоимение'), ('f', 'другое')], max_length=10, null=True),
        ),
    ]
