# Generated by Django 4.1 on 2022-09-14 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_word_level_alter_word_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
