# Generated by Django 4.1 on 2022-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_word_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(blank=True, choices=[('easy', 'легкий'), ('medium', 'средний'), ('hard', 'сложный')], max_length=10, null=True, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(blank=True, choices=[('a', 'глагол'), ('b', 'существительное'), ('c', 'прилагательное'), ('d', 'наречие'), ('e', 'местоимение'), ('f', 'другое')], max_length=10, null=True, verbose_name='Тип'),
        ),
    ]
