# Generated by Django 4.1 on 2022-09-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_word_level_alter_word_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-time_create']},
        ),
    ]
